version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      security:
        applies-to: security-updates
        patterns:
          - '*'
