version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      security:
        applies-to: security-updates
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        versions: ['0.x']
        update-types:
          - 'version-update:semver-minor'
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
